export const foodItems = [
  "Spaghetti",
  "Tacos",
  "Sushi",
  "Pizza",
  "Cheeseburger",
  "Caesar Salad",
  "Fried Chicken",
  "Pancakes",
  "Burrito",
  "Grilled Salmon",
  "Pad Thai",
  "Beef Stroganoff",
  "Chicken Tikka Masala",
  "Lasagna",
  "Ramen",
  "Fish and Chips",
  "Gyro",
  "Chocolate Cake",
  "Ice Cream",
  "Apple Pie",
  "French Fries",
  "Steak",
  "Lobster",
  "Mac and Cheese",
  "Quesadilla",
  "BLT Sandwich",
  "Croissant",
  "Bagel",
  "Doughnut",
  "Clam Chowder",
  "BBQ Ribs",
  "Chili",
  "Goulash",
  "Shrimp Scampi",
  "Fettuccine Alfredo",
  "Falafel",
  "Dim Sum",
  "Waffles",
  "Paella",
  "Pork Chops",
  "Chicken Alfredo",
  "Gnocchi",
  "Eggs Benedict",
  "French Toast",
  "Stuffed Peppers",
  "Chicken Noodle Soup",
  "Meatloaf",
  "Tiramisu",
  "Moussaka",
  "Kebabs",
  "Pho",
  "Enchiladas",
  "Fajitas",
  "Carbonara",
  "Crepes",
  "Curry",
  "Lamb Chops",
  "Margherita Pizza",
  "Mozzarella Sticks",
  "Onion Rings",
  "Oysters",
  "Pasta Primavera",
  "Pepperoni Pizza",
  "Pita Bread",
  "Polenta",
  "Poutine",
  "Pulled Pork Sandwich",
  "Ratatouille",
  "Reuben Sandwich",
  "Risotto",
  "Roast Beef",
  "Roast Chicken",
  "Samosa",
  "Sashimi",
  "Shepherd's Pie",
  "Soft Pretzel",
  "Spring Rolls",
  "Steak Tacos",
  "Street Tacos",
  "Stuffed Shells",
  "Sushi Roll",
  "Tempura",
  "Tom Yum Soup",
  "Tuna Salad",
  "Turkey Club Sandwich",
  "Veggie Burger",
  "Waldorf Salad",
  "Ziti",
  "Baked Beans",
  "Baked Potato",
  "Beef Wellington",
  "Biryani",
  "Blackened Fish",
  "Bratwurst",
  "Bread Pudding",
  "Bruschetta",
  "Buffalo Chicken Dip",
  "Butter Chicken",
  "Cannoli",
  "Caponata",
  "Cheese Fondue",
  "Cheesecake",
  "Chicken Curry",
  "Chicken Marsala",
  "Chicken Parmesan",
  "Chimichanga",
  "Chow Mein",
  "Crab Cakes",
  "Crème Brûlée",
  "Deviled Eggs",
  "Empanadas",
  "Fish Tacos",
  "Focaccia",
  "French Dip Sandwich",
  "Fried Rice",
  "Fruit Salad",
  "Galbi",
  "General Tso's Chicken",
  "Greek Salad",
  "Grilled Cheese Sandwich",
  "Gumbo",
  "Halibut",
  "Hash Browns",
  "Huevos Rancheros",
  "Jambalaya",
  "Jerk Chicken",
  "Kimchi",
  "Kung Pao Chicken",
  "Lamb Curry",
  "Lentil Soup",
  "Linguine",
  "Lobster Bisque",
  "Lobster Roll",
  "Matzo Ball Soup",
  "Mulligatawny",
  "Nachos",
  "Nicoise Salad",
  "Omelette",
  "Pad See Ew",
  "Pasta Carbonara",
  "Peach Cobbler",
  "Pierogi",
  "Pineapple Fried Rice",
  "Pork Belly",
  "Pot Roast",
  "Prime Rib",
  "Pulled Chicken",
  "Pumpkin Pie",
  "Quiche",
  "Red Beans and Rice",
  "Roast Duck",
  "Roast Lamb",
  "Rogan Josh",
  "Saltimbocca",
  "Scalloped Potatoes",
  "Seafood Paella",
  "Shrimp Cocktail",
  "Sliders",
  "Smoked Salmon",
  "Snickerdoodles",
  "Souvlaki",
  "Spanish Tortilla",
  "Spanakopita",
  "Stuffed Cabbage",
  "Sweet and Sour Chicken",
  "Tandoori Chicken",
  "Thai Curry",
  "Tuna Melt",
  "Upside-Down Cake",
  "Vegetable Stir Fry",
  "Venison",
  "Vichyssoise",
  "Vindaloo",
  "Wiener Schnitzel",
  "Yorkshire Pudding",
  "Zucchini Bread",
  "Aloo Gobi",
  "Baba Ganoush",
  "Bagna Cauda",
  "Baklava",
  "Beef Bourguignon",
  "Beef Brisket",
  "Beef Jerky",
  "Beef Stew",
  "Beignets",
  "Beet Salad",
  "Belgian Waffles",
  "Bisque",
  "Boston Cream Pie",
  "Braised Beef",
  "Braised Lamb",
  "Breakfast Burrito",
  "Broccoli Cheddar Soup",
  "Bubble and Squeak",
  "Bulgogi",
  "Buttermilk Biscuits",
  "Cabbage Rolls",
  "Caesar Wrap",
  "Calamari",
  "California Roll",
  "Cannelloni",
  "Caprese Salad",
  "Caramel Apples",
  "Carrot Cake",
  "Casserole",
  "Caviar",
  "Cheese Board",
  "Chicken Caesar Wrap",
  "Chicken Enchiladas",
  "Chicken Korma",
  "Chicken Pot Pie",
  "Chicken Quesadilla",
  "Chicken Salad",
  "Chicken Shawarma",
  "Chili Con Carne",
  "Chimichurri",
  "Chocolate Fondue",
  "Churros",
  "Cobb Salad",
  "Corn Chowder",
  "Cornbread",
  "Crab Rangoon",
  "Cranberry Sauce",
  "Creme Caramel",
  "Crispy Duck",
  "Croque Monsieur",
  "Crumpets",
  "Cuban Sandwich",
  "Dal Tadka",
  "Duck a l'Orange",
  "Egg Drop Soup",
  "Eggplant Parmesan",
  "Eggrolls",
  "Eton Mess",
  "Fajita Salad",
  "Filet Mignon",
  "Fish Curry",
  "Flan",
  "Flounder",
  "Fried Calamari",
  "Fried Catfish",
  "Fried Green Tomatoes",
  "Fried Plantains",
  "Fruit Tart",
  "Garlic Bread",
  "German Chocolate Cake",
  "Gingerbread",
  "Goat Cheese Salad",
  "Grilled Vegetables",
  "Grits",
  "Guacamole",
  "Gyoza",
  "Ham and Cheese Sandwich",
  "Hamburger",
  "Harissa Chicken",
  "Hash Brown Casserole",
  "Hollandaise Sauce",
  "Honey Glazed Ham",
  "Hot and Sour Soup",
  "Hot Dogs",
  "Hot Pot",
  "Hummus",
  "Ice Cream Sundae",
  "Irish Stew",
  "Italian Beef Sandwich",
  "Japanese Curry",
  "Jasmine Rice",
  "Jerk Pork",
  "Jollof Rice",
  "Katsu Curry",
  "Kielbasa",
  "Kofta",
  "Kung Pao Shrimp",
  "Lamb Kebab",
  "Lamb Tagine",
  "Latkes",
  "Lemon Bars",
  "Lemon Meringue Pie",
  "Lemonade",
  "Lentil Curry",
  "Lobster Mac and Cheese",
  "Mango Sticky Rice",
  "Maple Syrup",
  "Marinara Sauce",
  "Mashed Potatoes",
  "Matar Paneer",
  "Minestrone",
  "Mint Julep",
  "Mocha",
  "Mojito",
  "Mongolian Beef",
  "Moules Frites",
  "Muffuletta",
  "Mushroom Risotto",
  "Naan",
  "Nasi Goreng",
  "New England Clam Chowder",
  "Nori Rolls",
  "Okonomiyaki",
  "Olive Tapenade",
  "Onigiri",
  "Orange Chicken",
  "Osso Buco",
  "Panna Cotta",
  "Paratha",
  "Pepper Steak",
  "Pesto Pasta",
  "Pho Ga",
  "Pistachio Ice Cream",
  "Pizza Margherita",
  "Pork Carnitas",
  "Pork Dumplings",
  "Pork Schnitzel",
  "Potato Gratin",
  "Potato Salad",
  "Potstickers",
  "Pumpkin Bread",
  "Pupusas",
  "Quinoa Salad",
  "Ramen Noodles",
  "Ravioli",
  "Red Velvet Cake",
  "Refried Beans",
  "Rhubarb Pie",
  "Ricotta Pancakes",
  "Roast Pork",
  "Rouladen",
  "Sake",
  "Salmon Tartare",
  "Samosas",
  "Scampi",
  "Scrambled Eggs",
  "Seaweed Salad",
  "Sesame Chicken",
  "Sesame Noodles",
  "Shakshuka",
  "Shaved Ice",
  "Shrimp Bisque",
  "Shrimp Gumbo",
  "Shrimp Tempura",
  "Singapore Noodles",
  "Smoked Brisket",
  "Smoked Trout",
  "Soba Noodles",
  "Soft Shell Crab",
  "Sopaipillas",
  "Souffle",
] as const;
